### ISSUE TITLE
Missing Grid plus installed plugin description

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd-plus#12]
The installed plugin Grid Plus looks like this:

![Screen Shot 2019-08-05 at 21 38 02](https://user-images.githubusercontent.com/5323259/62490392-77ef6d00-b7c9-11e9-98bc-c493e2fb29d9.png)

-------

It should look something like this:

![Installed-plugin-Gridd-Plus](https://user-images.githubusercontent.com/5323259/62490420-863d8900-b7c9-11e9-9799-6a972230f032.jpg)

**Comment by aristath** [comment]
Already fixed in the dev version last week, it just didn't justify releasing an update just to add the description. Will be included in the next update 👍
