### ISSUE TITLE
Features suggestions - Add grid to WooCommerce pages

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd-plus#15]
For instance adding a widget area in WooCommerce page to add in some additional text or something else.

**Comment by aristath** [comment]
I don't get it... You mean a separate and standalone grid specifically for a woocommerce page? One that would override the global grid?

**Comment by paaljoachim** [comment]
Hey Ari. Right now I do not remember, so I will close this issue and when I get the idea back again I can explain and also reopen the issue.
