### ISSUE TITLE
Bug: Bottom mobile menu icon

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd-plus#16]
I noticed the following that the bottom mobile menu is not working.
![Screen Shot 2019-08-10 at 23 56 06](https://user-images.githubusercontent.com/5323259/62827192-d3a36700-bbca-11e9-8c78-0cc1180c8d39.png)

Btw there should be a link from the mobile customizer section to the nav header area. As the nav header is customizable on mobile.

![Screen Shot 2019-08-10 at 23 58 36](https://user-images.githubusercontent.com/5323259/62827196-ed44ae80-bbca-11e9-810f-5cff344b8d58.png)

Top mobile nav works.
![Screen Shot 2019-08-11 at 00 00 01](https://user-images.githubusercontent.com/5323259/62827209-064d5f80-bbcb-11e9-8b79-7999aec3d555.png)
Just not the bottom nav. Search and Home buttons work.

**Comment by aristath** [comment]
Did you assign a menu to the mobile nav? It's a separate navigation and can have a different menu assigned to it

**Comment by paaljoachim** [comment]
Ahh yes.
I assigned it through a widget. Still did not work.
Then I had to go to the menu locations and select the menu for the Mobile Navigation. Then it worked.

One for the docs..:)
