### ISSUE TITLE
Please take a look at the following WooCommerce shortcode issue

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd-plus#20]
Hey Ari

I was having a difficult time rendering product id shortcodes such as [product_page id=“142”] in Gutenberg and added as issue to WooCommerce Github repo: https://github.com/woocommerce/woocommerce/issues/24402

Product ids are not previewing in the backend and are not showing up correctly in the frontend.

**Comment by aristath** [comment]
For the backend part there's nothing the theme can do, that's up to WC.
You mentioned you also have an issue on the frontend? Can you elaborate?

**Comment by paaljoachim** [comment]
Adding various product id's will show the first and duplicates of the first product id even though 2 and 3 is different.

Like so
Added product id of 1,2,3

Frontend shows product id 1,1,1.
I find that weird.

**Comment by claudiosanches** [comment]
About the preview we can try work on WooCommerce.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue, as WooCommerce has a stronger focus on using blocks instead of product id shortcodes. I do not know why using different product id's that they still show the same product on the frontend. I will just let this go and if needed open a new issue in the future.
