### ISSUE TITLE
Cart drop down.

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd-plus#27]
Right now I am not sure where in the customizer the WooCommerce menu cart drop down is selected.

You could perhaps add it directly to:

<img width="362" alt="Screen Shot 2019-10-27 at 12 52 45" src="https://user-images.githubusercontent.com/5323259/67638243-ba03e880-f8b8-11e9-90d1-042b2ebebb06.png">

With some options if needed. (Can not think of any right now.) By default it would be on and if the user wants to do so they can turn it off. For instance if they have another option they use instead.

**Comment by aristath** [comment]
Hmmmm the on/off switch for the menu-cart is inside the navigation options. Since the cart gets added to navigation, I thought it would make sense to have the option there?

**Comment by paaljoachim** [comment]
Ahh there it is.
One goes to: Layout Blocks -> Header -> Navigation.
Yeah that is probably the best place to have it.
I will close the issue.
