### ISSUE TITLE
Updating from 1.0.7 -> 2.0

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd-plus#31]
I did a test. A local site just created for some testing of Gridd + Gridd plus.
Uploaded Gridd plus 2.0 and activated the license. That worked fine.
Then deleted Gridd plus 2.0 and uploaded Gridd plus 1.0.7 and noticed that I could not auto update (I had not yet inserted the license). Then went to insert license info.

![Screen Shot 2019-11-04 at 16 04 52](https://user-images.githubusercontent.com/5323259/68158128-01275480-ff1d-11e9-97e4-ddf02d169a4d.png)

It did not pick up the license info.

**Comment by aristath** [comment]
Fixed, it was a license limit.
