### ISSUE TITLE
Feature suggestions - color schemes

### ISSUE THREAD

**Issue by paaljoachim** [wplemon/gridd-plus#8]
It would be helpful to create a few color schemes or/and a color section.

![Screen Shot 2019-08-03 at 22 47 15](https://user-images.githubusercontent.com/5323259/62489936-5f328780-b7c8-11e9-8aee-e88fcd4a28a5.png)

![Screen Shot 2019-08-03 at 22 47 29](https://user-images.githubusercontent.com/5323259/62489943-66599580-b7c8-11e9-8c24-4c5c232768e2.png)

At the bottom of the colors could be an option to overwrite existing colors selected in various sections. As things are a bit spread out in different sections.

**Comment by paaljoachim** [comment]
Closing as this will likely be a no fix. We can always open it up again if it becomes relevant.

**Comment by aristath** [comment]
Yes, with the new palette-builder this one no longer makes a lot of sense... Developers can just pick 4 colors they want and remove everything else. Then they just use those colors everywhere consistently. ❤️
